import type { Metadata } from "next"
import { Geist, Geist_Mono } from "next/font/google"
import "../globals.css"
import { auth } from "@/lib/auth"
import { redirect } from "next/navigation"
import { headers } from "next/headers"
import { Providers } from "@/components/providers"

const geistSans = Geist({ variable: "--font-geist-sans", subsets: ["latin"] })
const geistMono = Geist_Mono({ variable: "--font-geist-mono", subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Portify",
  description: "Generated by Next.js + Auth.js",
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await auth()
  const pathname = (await headers()).get("x-pathname") || "/"

  if (!session && !pathname.startsWith("/login")) {
    redirect("/login")
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/*  Providers จะเป็น client component */}
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
