import { ThemeProvider } from "@/components/theme-provider";
import "@/app/globals.css";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Portify",
  description: "Generated by Next.js + Auth.js",
};

export default function LoginLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <main>
          <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
